# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JVFlowerMenuExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JVFlowerMenuExample
  #Development path
  pod 'JVFlowerMenu', :path => '~/Desktop/JVFlowerMenu/JVFlowerMenu.podspec'
  #Production Paths
  #pod 'JVFlowerMenu', :git => 'https://github.com/joninsky/JVFlowerMenu.git'

  target 'JVFlowerMenuExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
